import { Injectable } from '@nestjs/common';
import { ROLES, ROLES_EMPRESA } from '../constants/roles.constant';
import { PERMISSIONS } from '../constants/permissions.constant';

@Injectable()
export class RolesPredefinidosConfig {
  // Roles Globales del Sistema (Rol)
  static readonly ROLES_GLOBALES = {
    SUPER_ADMIN: {
      nombre: 'SUPER_ADMIN',
      descripcion: 'Administrador del sistema con acceso total',
      permisos: [
        'sistema.*',
        'empresas.*',
        'usuarios.*',
        'roles.*',
        'auditoria.*',
        'configuracion.*',
        'documentos.*',
        'archivos.*',
      ],
    },
    ADMIN_PLATAFORMA: {
      nombre: 'ADMIN_PLATAFORMA',
      descripcion:
        'Administrador de la plataforma con acceso a gestión de empresas',
      permisos: [
        'empresas.ver',
        'empresas.crear',
        'empresas.editar',
        'empresas.eliminar',
        'usuarios.ver',
        'roles.ver',
        'reportes.ver',
        'auditoria.ver',
        'documentos.ver',
        'archivos.ver',
      ],
    },
    CLIENTE: {
      nombre: 'CLIENTE',
      descripcion: 'Usuario tipo cliente con acceso a servicios de empresas',
      permisos: [
        'productos.ver',
        'servicios.ver',
        'pedidos.crear',
        'pedidos.ver',
        'pedidos.cancelar',
        'perfil.ver',
        'perfil.editar',
        'direcciones.ver',
        'direcciones.crear',
        'direcciones.editar',
        'direcciones.eliminar',
        'pagos.ver',
        'pagos.realizar',
        'valoraciones.crear',
        'valoraciones.ver',
        'notificaciones.ver',
        'fidelizacion.ver',
        'fidelizacion.puntos.ver',
        'fidelizacion.puntos.canjear',
        'documentos.ver',
        'documentos.descargar',
      ],
    },
    PROVEEDOR: {
      nombre: 'PROVEEDOR',
      descripcion:
        'Empresa proveedora con acceso a gestión de productos y pedidos',
      permisos: [
        'productos.ver',
        'productos.crear',
        'productos.editar',
        'productos.eliminar',
        'pedidos.ver',
        'pedidos.procesar',
        'inventario.ver',
        'inventario.editar',
        'reportes.ver',
        'perfil.ver',
        'perfil.editar',
        'cotizaciones.ver',
        'cotizaciones.crear',
        'cotizaciones.editar',
        'documentos.ver',
        'documentos.subir',
      ],
    },
    API: {
      nombre: 'API',
      descripcion: 'Rol para integraciones externas y APIs',
      permisos: [
        'api.productos.ver',
        'api.pedidos.crear',
        'api.pedidos.ver',
        'api.inventario.ver',
        'api.clientes.ver',
        'api.ventas.ver',
        'api.documentos.ver',
      ],
    },
  };

  // Roles por Empresa (RolEmpresa)
  static readonly ROLES_EMPRESA = {
    ADMINISTRADOR: {
      nombre: 'ADMINISTRADOR',
      descripcion: 'Administrador de la empresa con acceso total',
      permisos: [
        'empresa.*',
        'usuarios.*',
        'roles.*',
        'productos.*',
        'servicios.*',
        'ventas.*',
        'compras.*',
        'inventario.*',
        'reportes.*',
        'configuracion.*',
        'auditoria.*',
        'fidelizacion.*',
        'cotizaciones.*',
        'facturacion.*',
        'impuestos.*',
        'documentos.*',
        'archivos.*',
        'regional.*',
      ],
    },
    GERENTE: {
      nombre: 'GERENTE',
      descripcion: 'Gerente de la empresa con acceso a gestión operativa',
      permisos: [
        'empresa.ver',
        'usuarios.ver',
        'productos.*',
        'servicios.*',
        'ventas.*',
        'compras.*',
        'inventario.*',
        'reportes.*',
        'configuracion.ver',
        'fidelizacion.*',
        'cotizaciones.*',
        'facturacion.ver',
        'impuestos.ver',
        'documentos.ver',
        'archivos.ver',
        'regional.ver',
      ],
    },
    SUPERVISOR: {
      nombre: 'SUPERVISOR',
      descripcion: 'Supervisor de operaciones',
      permisos: [
        'productos.ver',
        'productos.editar',
        'servicios.ver',
        'servicios.editar',
        'ventas.ver',
        'ventas.crear',
        'ventas.editar',
        'inventario.ver',
        'inventario.editar',
        'reportes.ver',
        'usuarios.ver',
        'fidelizacion.ver',
        'cotizaciones.ver',
        'cotizaciones.crear',
        'documentos.ver',
        'archivos.ver',
      ],
    },
    VENDEDOR: {
      nombre: 'VENDEDOR',
      descripcion: 'Vendedor con acceso a operaciones de venta',
      permisos: [
        'productos.ver',
        'servicios.ver',
        'ventas.ver',
        'ventas.crear',
        'clientes.ver',
        'clientes.crear',
        'inventario.ver',
        'reportes.ver',
        'fidelizacion.ver',
        'fidelizacion.puntos.asignar',
        'cotizaciones.ver',
        'cotizaciones.crear',
        'documentos.ver',
        'documentos.descargar',
      ],
    },
    ALMACEN: {
      nombre: 'ALMACEN',
      descripcion: 'Personal de almacén e inventario',
      permisos: [
        'productos.ver',
        'inventario.*',
        'compras.ver',
        'compras.crear',
        'reportes.ver',
        'proveedores.ver',
        'stock.ver',
        'stock.editar',
        'stock.ajustar',
        'documentos.ver',
        'archivos.ver',
      ],
    },
    CONTADOR: {
      nombre: 'CONTADOR',
      descripcion: 'Personal de contabilidad y finanzas',
      permisos: [
        'ventas.ver',
        'compras.ver',
        'reportes.*',
        'contabilidad.*',
        'impuestos.*',
        'facturacion.*',
        'pagos.ver',
        'pagos.procesar',
        'notas_credito.*',
        'notas_debito.*',
        'documentos.ver',
        'documentos.subir',
        'archivos.ver',
      ],
    },
    RECURSOS_HUMANOS: {
      nombre: 'RECURSOS_HUMANOS',
      descripcion: 'Personal de recursos humanos',
      permisos: [
        'usuarios.ver',
        'usuarios.crear',
        'usuarios.editar',
        'roles.ver',
        'reportes.ver',
        'asistencias.ver',
        'asistencias.editar',
        'nominas.ver',
        'nominas.crear',
        'horarios.ver',
        'horarios.editar',
        'beneficios.ver',
        'beneficios.editar',
        'documentos.ver',
        'documentos.subir',
        'archivos.ver',
      ],
    },
    AUDITOR: {
      nombre: 'AUDITOR',
      descripcion: 'Auditor interno para revisión de operaciones',
      permisos: [
        'ventas.ver',
        'compras.ver',
        'inventario.ver',
        'reportes.*',
        'auditoria.ver',
        'auditoria.crear',
        'usuarios.ver',
        'facturacion.ver',
        'impuestos.ver',
        'pagos.ver',
        'documentos.ver',
        'archivos.ver',
      ],
    },
    MARKETING: {
      nombre: 'MARKETING',
      descripcion: 'Personal de marketing y promociones',
      permisos: [
        'productos.ver',
        'servicios.ver',
        'promociones.*',
        'campañas.*',
        'reportes.ver',
        'clientes.ver',
        'notificaciones.crear',
        'fidelizacion.ver',
        'fidelizacion.promociones.*',
        'valoraciones.ver',
        'feedback.ver',
        'documentos.ver',
        'archivos.ver',
        'archivos.subir',
      ],
    },
    SOPORTE: {
      nombre: 'SOPORTE',
      descripcion: 'Personal de soporte y atención al cliente',
      permisos: [
        'clientes.ver',
        'clientes.editar',
        'tickets.ver',
        'tickets.crear',
        'tickets.editar',
        'tickets.cerrar',
        'notificaciones.ver',
        'notificaciones.crear',
        'reportes.ver',
        'feedback.ver',
        'feedback.responder',
        'valoraciones.ver',
        'documentos.ver',
        'archivos.ver',
      ],
    },
    ANALISTA_DATOS: {
      nombre: 'ANALISTA_DATOS',
      descripcion: 'Analista de datos y business intelligence',
      permisos: [
        'reportes.*',
        'ventas.ver',
        'compras.ver',
        'inventario.ver',
        'clientes.ver',
        'productos.ver',
        'servicios.ver',
        'documentos.ver',
        'archivos.ver',
        'exportar.*',
        'dashboard.*',
      ],
    },
    GESTOR_LEGAL: {
      nombre: 'GESTOR_LEGAL',
      descripcion: 'Gestor de documentos legales y cumplimiento',
      permisos: [
        'documentos.*',
        'archivos.*',
        'contratos.ver',
        'contratos.crear',
        'contratos.editar',
        'contratos.eliminar',
        'legal.ver',
        'legal.crear',
        'legal.editar',
        'legal.eliminar',
        'cumplimiento.ver',
        'cumplimiento.reportar',
      ],
    },
    GESTOR_CALIDAD: {
      nombre: 'GESTOR_CALIDAD',
      descripcion: 'Gestor de control de calidad y estándares',
      permisos: [
        'calidad.*',
        'productos.ver',
        'servicios.ver',
        'procesos.ver',
        'procesos.editar',
        'estandares.ver',
        'estandares.editar',
        'documentos.ver',
        'documentos.subir',
        'archivos.ver',
        'reportes.ver',
        'auditoria.ver',
      ],
    },
  };

  // Permisos por Módulo (Permiso)
  static readonly PERMISOS_MODULO = {
    EMPRESA: ['ver', 'crear', 'editar', 'eliminar'],
    USUARIOS: ['ver', 'crear', 'editar', 'eliminar', 'bloquear', 'desbloquear'],
    ROLES: ['ver', 'crear', 'editar', 'eliminar'],
    PRODUCTOS: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'publicar',
      'despublicar',
      'categorizar',
    ],
    SERVICIOS: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'publicar',
      'despublicar',
      'categorizar',
    ],
    VENTAS: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'anular',
      'facturar',
      'exportar',
    ],
    COMPRAS: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'anular',
      'facturar',
      'exportar',
    ],
    CLIENTES: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'bloquear',
      'desbloquear',
      'historial',
    ],
    PROVEEDORES: ['ver', 'crear', 'editar', 'eliminar', 'evaluar', 'historial'],
    INVENTARIO: ['ver', 'crear', 'editar', 'eliminar', 'ajustar', 'movimiento'],
    CONTABILIDAD: ['ver', 'crear', 'editar', 'eliminar', 'cerrar', 'reportar'],
    REPORTES: ['ver', 'crear', 'editar', 'eliminar', 'exportar', 'programar'],
    AUDITORIA: ['ver', 'crear', 'editar', 'eliminar', 'exportar'],
    CONFIGURACION: ['ver', 'crear', 'editar', 'eliminar'],
    PROMOCIONES: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'activar',
      'desactivar',
    ],
    CAMPAÑAS: ['ver', 'crear', 'editar', 'eliminar', 'activar', 'desactivar'],
    TICKETS: ['ver', 'crear', 'editar', 'eliminar', 'cerrar', 'reasignar'],
    NOTIFICACIONES: ['ver', 'crear', 'editar', 'eliminar', 'enviar'],
    ASISTENCIAS: ['ver', 'crear', 'editar', 'eliminar', 'aprobar'],
    NOMINAS: ['ver', 'crear', 'editar', 'eliminar', 'aprobar'],
    FACTURACION: ['ver', 'crear', 'editar', 'eliminar', 'anular', 'exportar'],
    IMPUESTOS: ['ver', 'crear', 'editar', 'eliminar', 'calcular', 'reportar'],
    FIDELIZACION: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'puntos.asignar',
      'puntos.canjear',
      'promociones.*',
    ],
    COTIZACIONES: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'aprobar',
      'convertir',
    ],
    STOCK: ['ver', 'crear', 'editar', 'eliminar', 'ajustar', 'movimiento'],
    PAGOS: ['ver', 'crear', 'editar', 'eliminar', 'procesar', 'reembolsar'],
    FEEDBACK: ['ver', 'crear', 'editar', 'eliminar', 'responder'],
    VALORACIONES: ['ver', 'crear', 'editar', 'eliminar', 'moderar'],
    HORARIOS: ['ver', 'crear', 'editar', 'eliminar', 'asignar'],
    BENEFICIOS: ['ver', 'crear', 'editar', 'eliminar', 'asignar'],
    DOCUMENTOS: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'subir',
      'descargar',
      'compartir',
    ],
    ARCHIVOS: [
      'ver',
      'crear',
      'editar',
      'eliminar',
      'subir',
      'descargar',
      'compartir',
    ],
    REGIONAL: ['ver', 'crear', 'editar', 'eliminar', 'configurar'],
    CALIDAD: ['ver', 'crear', 'editar', 'eliminar', 'evaluar', 'reportar'],
    LEGAL: ['ver', 'crear', 'editar', 'eliminar', 'revisar', 'aprobar'],
    CONTRATOS: ['ver', 'crear', 'editar', 'eliminar', 'firmar', 'archivar'],
    CUMPLIMIENTO: ['ver', 'crear', 'editar', 'eliminar', 'reportar', 'auditar'],
    DASHBOARD: ['ver', 'crear', 'editar', 'eliminar', 'compartir', 'exportar'],
  };

  static readonly ROLES_PREDEFINIDOS = {
    [ROLES.SUPER_ADMIN]: {
      descripcion: 'Super Administrador del sistema',
      permisos: Object.values(PERMISSIONS).flatMap((module) =>
        Object.values(module),
      ),
    },
    [ROLES.ADMIN]: {
      descripcion: 'Administrador de plataforma',
      permisos: [
        PERMISSIONS.EMPRESA.READ,
        PERMISSIONS.EMPRESA.WRITE,
        PERMISSIONS.USUARIOS.READ,
        PERMISSIONS.USUARIOS.WRITE,
      ],
    },
    [ROLES.CLIENTE]: {
      descripcion: 'Cliente del sistema',
      permisos: [
        PERMISSIONS.PRODUCTOS.READ,
        PERMISSIONS.SERVICIOS.READ,
        PERMISSIONS.DOCUMENTOS.READ,
      ],
    },
    [ROLES.PROVEEDOR]: {
      descripcion: 'Proveedor de servicios',
      permisos: [
        PERMISSIONS.PRODUCTOS.READ,
        PERMISSIONS.SERVICIOS.READ,
        PERMISSIONS.SERVICIOS.WRITE,
        PERMISSIONS.DOCUMENTOS.READ,
      ],
    },
    [ROLES.API]: {
      descripcion: 'Acceso API',
      permisos: [PERMISSIONS.API.READ, PERMISSIONS.API.WRITE],
    },
    [ROLES_EMPRESA.ADMINISTRADOR]: {
      descripcion: 'Administrador de empresa',
      permisos: [
        PERMISSIONS.EMPRESA.READ,
        PERMISSIONS.EMPRESA.WRITE,
        PERMISSIONS.USUARIOS.READ,
        PERMISSIONS.USUARIOS.WRITE,
        PERMISSIONS.ROLES.READ,
        PERMISSIONS.ROLES.WRITE,
        PERMISSIONS.CONFIGURACION.READ,
        PERMISSIONS.CONFIGURACION.WRITE,
      ],
    },
    [ROLES_EMPRESA.GERENTE]: {
      descripcion: 'Gerente de empresa',
      permisos: [
        PERMISSIONS.EMPRESA.READ,
        PERMISSIONS.USUARIOS.READ,
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.REPORTES.EXPORT,
        PERMISSIONS.CONFIGURACION.READ,
      ],
    },
    [ROLES_EMPRESA.SUPERVISOR]: {
      descripcion: 'Supervisor de operaciones',
      permisos: [
        PERMISSIONS.VENTAS.READ,
        PERMISSIONS.VENTAS.WRITE,
        PERMISSIONS.INVENTARIO.READ,
        PERMISSIONS.INVENTARIO.WRITE,
        PERMISSIONS.USUARIOS.READ,
        PERMISSIONS.REPORTES.READ,
      ],
    },
    [ROLES_EMPRESA.VENDEDOR]: {
      descripcion: 'Vendedor',
      permisos: [
        PERMISSIONS.VENTAS.READ,
        PERMISSIONS.VENTAS.WRITE,
        PERMISSIONS.PRODUCTOS.READ,
        PERMISSIONS.SERVICIOS.READ,
        PERMISSIONS.DOCUMENTOS.READ,
      ],
    },
    [ROLES_EMPRESA.ALMACEN]: {
      descripcion: 'Gestor de almacén',
      permisos: [
        PERMISSIONS.INVENTARIO.READ,
        PERMISSIONS.INVENTARIO.WRITE,
        PERMISSIONS.INVENTARIO.ADJUST,
        PERMISSIONS.PRODUCTOS.READ,
        PERMISSIONS.PRODUCTOS.WRITE,
      ],
    },
    [ROLES_EMPRESA.CONTADOR]: {
      descripcion: 'Contador',
      permisos: [
        PERMISSIONS.CONTABILIDAD.READ,
        PERMISSIONS.CONTABILIDAD.WRITE,
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.REPORTES.EXPORT,
        PERMISSIONS.CONFIGURACION.READ,
      ],
    },
    [ROLES_EMPRESA.RECURSOS_HUMANOS]: {
      descripcion: 'Recursos Humanos',
      permisos: [
        PERMISSIONS.USUARIOS.READ,
        PERMISSIONS.USUARIOS.WRITE,
        PERMISSIONS.USUARIOS.BLOCK,
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.DOCUMENTOS.READ,
        PERMISSIONS.DOCUMENTOS.WRITE,
      ],
    },
    [ROLES_EMPRESA.AUDITOR]: {
      descripcion: 'Auditor',
      permisos: [
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.REPORTES.EXPORT,
        PERMISSIONS.CONFIGURACION.READ,
        PERMISSIONS.DOCUMENTOS.READ,
      ],
    },
    [ROLES_EMPRESA.MARKETING]: {
      descripcion: 'Marketing',
      permisos: [
        PERMISSIONS.PRODUCTOS.READ,
        PERMISSIONS.SERVICIOS.READ,
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.DOCUMENTOS.READ,
      ],
    },
    [ROLES_EMPRESA.SOPORTE]: {
      descripcion: 'Soporte técnico',
      permisos: [
        PERMISSIONS.SISTEMA.READ,
        PERMISSIONS.CONFIGURACION.READ,
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.DOCUMENTOS.READ,
      ],
    },
    [ROLES_EMPRESA.ANALISTA_DATOS]: {
      descripcion: 'Analista de datos',
      permisos: [
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.REPORTES.WRITE,
        PERMISSIONS.REPORTES.EXPORT,
        PERMISSIONS.CONFIGURACION.READ,
      ],
    },
    [ROLES_EMPRESA.GESTOR_LEGAL]: {
      descripcion: 'Gestor legal',
      permisos: [
        PERMISSIONS.DOCUMENTOS.READ,
        PERMISSIONS.DOCUMENTOS.WRITE,
        PERMISSIONS.DOCUMENTOS.UPLOAD,
        PERMISSIONS.DOCUMENTOS.DOWNLOAD,
        PERMISSIONS.CONFIGURACION.READ,
      ],
    },
    [ROLES_EMPRESA.GESTOR_CALIDAD]: {
      descripcion: 'Gestor de calidad',
      permisos: [
        PERMISSIONS.PRODUCTOS.READ,
        PERMISSIONS.SERVICIOS.READ,
        PERMISSIONS.REPORTES.READ,
        PERMISSIONS.REPORTES.WRITE,
        PERMISSIONS.CONFIGURACION.READ,
      ],
    },
  } as const;
}
